### ISSUE TITLE
Download all lyrics of the whole music database

### ISSUE THREAD

**Issue by mabs67** [dmo60/lLyrics#25]
Hi,

it might be already in but I did not find it.

a feature to download all (missing) lyrics of the whole music database would be nice. So I have the lyrics already with me even I'm not connected to the Net while on the move or with no coverage.

M

**Comment by dmo60** [comment]
Sorry, I don't have the time to add this feature. If you are still interested, please consider opening a pull request. Thanks for the effort though!
