### ISSUE TITLE
lyrics site potentially on the ban-hammer

### ISSUE THREAD

**Issue by fossfreedom** [dmo60/lLyrics#32]
Thought I'd let you know this if you dont already know.

A few of the sites you support in the plugin are potentially disappearing due to the NMPA's throwing its weight around :/

http://yro.slashdot.org/story/13/11/12/0352244/music-industry-issues-take-down-notices-to-50-major-lyrics-sites?utm_source=rss1.0mainlinkanon&utm_medium=feed

- http://www.nmpa.org/pdf/whats_new/UGA_Music_Business_Undesirable_Lyric_Website_List_Oct_22nd_2013.pdf

**Comment by facundoq** [comment]
Just a little comment; using terra.br as provider in general results in lyrics without newlines. Possibly encoding issues?

Great plugin!

**Comment by dmo60** [comment]
@fossfreedom @facundoq 
I've fixed all the broken providers and removed some that are not available anymore.
I will create a new release soon. Thanks for reporting and sorry for the delay!
