### ISSUE TITLE
Create a tag/release

### ISSUE THREAD

**Issue by hobarrera** [dmo60/lLyrics#48]
In order to create proper downstream (eg: distribution) packages, it's generally necesary to have a certain release of upstream software (eg: 1.0, or 0.1.0, etc).

That's not only for properly labeling the version, but for everyone to know exactly what version it corresponds to and to have a consistent versioning scheme to push updates.

Could you create a tag (again, 1.0, 0.1, or whatever you prefer) to use as a reference for a concrete version?

Thanks. And thanks for the great work developing this plugin! ☺

**Comment by dmo60** [comment]
Thanks for the suggestions, I've created a v1.0 release to start with!

**Comment by hobarrera** [comment]
Thanks! :)
