### ISSUE TITLE
Sidebar size

### ISSUE THREAD

**Issue by ARTIsshoque** [dmo60/lLyrics#52]
Hello. Is there any way to save the sidebar's size to make it constant for every Rhythmbox start? Now it always has one width at every launch, but it's not the width I want, and it's kinda annoying. I use lLyrics plugin along with the RhythmTray plugin, and every time I minimize Rhythmox and then open it, it works like it was just started, and width of the lLyrics plugin's sidebar is too small. Maybe I can save the appropriate width somewhere, so it will always be the same?

**Comment by dmo60** [comment]
Hey, thanks for reporting and sorry for the delayed answer: I've removed the size request for the sidebar, which means Rhythmbox should now do its job and remember the size of the sidebar for you.
Should be fixed once you get the next update, but please let me know, if you still have this issue!

**Comment by ARTIsshoque** [comment]
Thanks. I'll have to upgrade to new version before I could see any changes though. While GNOME 3 and ATI drivers are incompatible I can't use it, so will wait for some time. Maybe forever.
