### ISSUE TITLE
Cann't find ILyrics in plug-in list after install

### ISSUE THREAD

**Issue by LYU-Daliang** [dmo60/lLyrics#55]
Cann't find ILyrics in plug-in list after install.

**Comment by SYN-cook** [comment]
It is possible that the file permissions are wrong, at least I observed this on my system. 

If this is the case, running `chmod -R 755 lLyrics/` as root in /usr/lib/rhythmbox/plugins/ should fix the problem.

**Comment by dmo60** [comment]
Thanks for reporting! @SYN-cook is right: When using `make install-systemwide` the file permissions were not set correctly. This is fixed now.
