### ISSUE TITLE
Use own lyric database

### ISSUE THREAD

**Issue by amalaiteko** [dmo60/lLyrics#56]
Hey,

first of all, great job! Thx a lot for your work! There is only one thing I miss:
I have a lyrics database of several thousand lyrics. Some are edited/added by myself. I'd like to use these lyrics to be shown in rhythmbox, preferably using your plugin. Of course the filename pattern is different from what your plugin seems to expect - unless I have missed something?

Thx in advance!
amalaiteko

**Comment by ARTIsshoque** [comment]
Hello, I had the same problem years ago. I had own lyrics database in separate files too, and I just organized it and rhythmbox works fine with them now. You only need to create folder for lyrics and subfolders named with artist names in lower case: like "abba" or "the beatles". And the files with lyrics must be named with song titles in lower case with ".lyric" extension, like "the beatles/let it be.lyric". The good news is that you even don't need to create files by yourself. Just enable built-in lyrics plugin, set the path to lyrics folder and press "properties" on any song. On the "lyrics" tab you can press "Edit", paste your lyrics and press "Save" - rhythmbox will create file and folder for you.

**Comment by amalaiteko** [comment]
It seems that there are not many people sharing my problem. The mentioned solution from @ARTIsshoque doesn't make me happy, as this involves manual interference with all the lyric files again (I won't edit my lyrics manually again).

**Comment by dmo60** [comment]
The solution from @ARTIsshoque is the only way to provide your own lyrics and I also don't plan to add anything more. This is just way too specific, different people store their lyrics differently, I cannot support that. Sorry!
