### ISSUE TITLE
Sidebar covers browser/playlist

### ISSUE THREAD

**Issue by ARTIsshoque** [dmo60/lLyrics#58]
Hello.
Sorry for interrupting, but I can't use lLyrics plugin with this trouble. I used Debian 7 before with Rhythmbox 2.99 and plugin worked very very fine (except issue #52, but it was nothing in compare with this one). I updated to Rhythmbox 3.3.1 (and tried 3.1 too, it doesn't matter) and left sidebar now covers playlist or browser if lLyrics plugin is enabled. I attach screenshots so you can compare.

Is there any solution for this issue?
![2 99](https://cloud.githubusercontent.com/assets/12800865/15753504/eeda3598-2925-11e6-8693-846eee00725d.png)
![3 3 1](https://cloud.githubusercontent.com/assets/12800865/15753505/eefc6956-2925-11e6-85ba-18f031b53883.png)

**Comment by dmo60** [comment]
The browser UI requires a minimal width and with the lyrics sidebar opened there obviously does not seem to be enough space left. I cannot do anything about that. You can try to resize the lyrics sidebar or you can choose the option to show the lyrics in the left sidebar in the plugin preferences. I hope that helps!
