### ISSUE TITLE
Lirics for radio songs

### ISSUE THREAD

**Issue by nikosbo** [dmo60/lLyrics#61]
I have one question, ILyrics should show lyrics also for songs listened on radio streaming ? Does it depend on informations sent by the radio? Is yes, title is sent but lyrics  do not show up.

**Comment by dmo60** [comment]
It's not possible to show lyrics for radio streams. The way the plugin works does not allow that at the moment and I'm not even sure it would be possible at all. I also don't plan to work on that, sorry!
