### ISSUE TITLE
Error loading plugin 'lLyrics'

### ISSUE THREAD

**Issue by ghost** [dmo60/lLyrics#63]
I am running Debian Jessie with Rythmbox 3.1. Whether I try to install lLyrics after cloning with `make install` or `make install-systemwide`, it appears in Rythmbox's plugin dialog, but when I try to enable it the green puzzle piece icon turns into a red stop sign and hovering over it displays:

```
The plugin 'lLyrics' could not be loaded.
An error occured: Failed to load.
```

Output from installation (same for `make install` except other path at bottom):
```
$ make install-systemwide
[sudo prompt]
Installing schema...
... done!
Installing locales...
de.po
./lLyrics/locale/de.po:7: warning: header field 'Project-Id-Version' still has the initial default value
fr.po
./lLyrics/locale/fr.po:7: warning: header field 'Project-Id-Version' still has the initial default value
pl.po
./lLyrics/locale/pl.po:7: warning: header field 'Project-Id-Version' still has the initial default value
... done!
Installing plugin files to /usr/lib/rhythmbox/plugins/ ...
Done!
```

I checked that files get copied over appropriately. I also tried using [https://github.com/dmo60/lLyrics/archive/v1.1.zip](https://github.com/dmo60/lLyrics/archive/v1.1.zip) instead of using master-branch, but get the same result.

**Comment by timoloewe** [comment]
Please try to install python-lxml either using your system package manager or using pip: 
`pip install lxml`.
If that does not help, run Rhythmbox from the command line to get some debug output:
`rhythmbox -D lLyrics`
You will see an error message when trying to activate the plugin, please post it here.

**Comment by ghost** [comment]
Thanks for your quick reply. You guessed correctly that my issue was related to `lxml`, as the debug output listed an ImportError for lxml. I found that surprising, because I have python-lxml already installed. Running `pip install lxml` didn't help either, as its output reported that it was already installed. I fixed the problem by installing the Python3 flavor of lxml using my system package manager: `sudo aptitude install python3-lxml` - now everything works as it should. So this issue can be closed.

Perhaps it might be a good idea if you could list this as a requirement for Debian users.

**Comment by timoloewe** [comment]
Glad it works! Yes, the README file should be reviewed and should point out the dependencies. I put it on my list. Thanks!
