### ISSUE TITLE
Plugin does not work in Debian Jessie

### ISSUE THREAD

**Issue by MathiasSM** [dmo60/lLyrics#64]
For some reason it doesn't work on Debian Jessie with Gnome (even out of the box). It doesn't give any feedback on why. Is there any log file I could check to provide more info? (Or perhaps fix it myself)

**Comment by MathiasSM** [comment]
The plugin framework (or maybe just rhythmbox, or whatever) uses Python3.4 (hardcoded, can't even uninstall 3.4 without stripping the system of almost everything), even when I have Python3.6. 

**The python module `lxml` is need for this plugin to work**, and it's not on python3.4 by default, which is what rhythmbox, or the plugin framework it uses, or debian/gnome uses by default.

`pip3` by default uses the latest `python3` installed (my `python3` points to `python3.6`), so the only way I could install `lxml` on Python3.4 was using `python3.4 -m pip install lxml`, which I didn't know I could do (use pip through the specific python exec). 

It was especially hard since python's `sys` module reports not-really-accurate info: It looks for what the $PATH says, so it said my python3 (3.6), was running python3.4, which is nonsense. It was actually running the python3.4 directly. 

Anyway, the plugin is now working :dango:

**Comment by timoloewe** [comment]
I will add the lxml dependency to the README. Thanks for reporting and glad it's working now!
