### ISSUE TITLE
not working on ubuntu 17.10

### ISSUE THREAD

**Issue by saurabhmodh94** [dmo60/lLyrics#71]
After installing the plug-in, when I try to activate it, it shows me an error. Please check the image
![screenshot from 2018-06-19 12-06-12](https://user-images.githubusercontent.com/7349248/41580642-392504c2-73b9-11e8-9817-0a4540d0bdc5.png)

**Comment by parthagar** [comment]
#63 Check this one out. It solved the same problem as yours for me.

**Comment by saurabhmodh94** [comment]
@parthagar Thanks for the reply. Yes, it was the same issue mentioned in https://github.com/dmo60/lLyrics/issues/63 
`ModuleNotFoundError: No module named 'lxml' .
`

However, I had to run different commands on ubuntu 18.04 terminal, to make this plugin work.
` sudo apt-get install python3-lxml 
`
(or python-lxml) depending on python version.
source: https://stackoverflow.com/questions/4598229/installing-lxml-module-in-python
